INSERT INTO `manager`(`tname`, `number`) VALUES ('JavaWeb笔记', 10);
INSERT INTO `manager`(`tname`, `number`) VALUES ('Java笔记', 2);
INSERT INTO `manager`(`tname`, `number`) VALUES ('人生哲学', 1);
INSERT INTO `manager`(`tname`, `number`) VALUES ('体育', 2);
INSERT INTO `manager`(`tname`, `number`) VALUES ('影视', 0);
INSERT INTO `manager`(`tname`, `number`) VALUES ('散文欣赏', 1);
INSERT INTO `manager`(`tname`, `number`) VALUES ('数据结构', 1);
INSERT INTO `manager`(`tname`, `number`) VALUES ('生活点滴', 13);
INSERT INTO `manager`(`tname`, `number`) VALUES ('算法笔记', 2);
